version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: lunch_helper_app
    # '/start' is the shell script used to run the service
    command: ./scripts/django_start.sh
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: jason890088@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${SQL_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: lunch_helper_celery_worker
    command: ./scripts/worker_start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  celery_beat:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: lunch_helper_celery_beat
    command: ./scripts/beat_start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_base
    image: lunch_helper_flower
    command: ./scripts/flower_start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  pgadmin_data: